/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemvismodul3;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yusfian Braman Tio
 */
public class modul3_no2 extends javax.swing.JFrame {
    boolean[] statusPembayaranBulan = new boolean[12];
    private String namaSiswa = "";
    private String kelasSiswa = "";
    private String nisnSiswa = "";

    /**
     * Creates new form modul3_no2
     */
    
    public modul3_no2() {
        initComponents();
        tfuang.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                penghitungan();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void penghitungan() {
        try {
            double pembayaran = Double.parseDouble(tftotal.getText());
            double uangmasuk = Double.parseDouble(tfuang.getText());
            double kembalian = uangmasuk - pembayaran;

            if (kembalian >= 0) {
                tfkembalian.setText(String.valueOf(kembalian));
            } else {
                tfkembalian.setText("Uang Tidak Cukup");
            }
        } catch (NumberFormatException e) {
            tfkembalian.setText("");
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfkelas = new javax.swing.JTextField();
        tfnisn = new javax.swing.JTextField();
        btndata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        panel5 = new javax.swing.JPanel();
        januari = new javax.swing.JCheckBox();
        februari = new javax.swing.JCheckBox();
        maret = new javax.swing.JCheckBox();
        april = new javax.swing.JCheckBox();
        mei = new javax.swing.JCheckBox();
        juni = new javax.swing.JCheckBox();
        juli = new javax.swing.JCheckBox();
        agustus = new javax.swing.JCheckBox();
        september = new javax.swing.JCheckBox();
        oktober = new javax.swing.JCheckBox();
        november = new javax.swing.JCheckBox();
        desember = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        tfuang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfkembalian = new javax.swing.JTextField();
        btntotal = new javax.swing.JButton();
        tftotal = new javax.swing.JTextField();
        btnpembayaran = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelstatus = new javax.swing.JTable();
        btnstatus = new javax.swing.JButton();
        btnriwayat = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(51, 153, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel10.setFont(new java.awt.Font("Chaparral Pro", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FORM SPP SISWA");
        panel2.add(jLabel10);

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1125, -1));

        panel3.setBackground(new java.awt.Color(102, 204, 255));
        panel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        jLabel2.setText("Nama:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 0, 0, 0);
        panel3.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        jLabel3.setText("Kelas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 2, 0, 0);
        panel3.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panel3.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        jLabel5.setText("NISN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        panel3.add(jLabel5, gridBagConstraints);

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 12, 0, 6);
        panel3.add(tfnama, gridBagConstraints);

        tfkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkelasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 6);
        panel3.add(tfkelas, gridBagConstraints);

        tfnisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnisnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 6);
        panel3.add(tfnisn, gridBagConstraints);

        btndata.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 14)); // NOI18N
        btndata.setText("Kirim");
        btndata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 222, 0, 6);
        panel3.add(btndata, gridBagConstraints);

        panel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 127, -1, -1));

        jLabel1.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Siswa");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 75, 83, -1));

        jLabel6.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pembayaran");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 220, 42));

        panel4.setBackground(new java.awt.Color(102, 204, 255));

        panel5.setBackground(new java.awt.Color(102, 204, 255));
        panel5.setLayout(new java.awt.GridLayout(6, 2));

        januari.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        januari.setText("Januari");
        panel5.add(januari);

        februari.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        februari.setText("Februari");
        februari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                februariActionPerformed(evt);
            }
        });
        panel5.add(februari);

        maret.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        maret.setText("Maret");
        panel5.add(maret);

        april.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        april.setText("April");
        panel5.add(april);

        mei.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        mei.setText("Mei");
        mei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meiActionPerformed(evt);
            }
        });
        panel5.add(mei);

        juni.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        juni.setText("Juni");
        juni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juniActionPerformed(evt);
            }
        });
        panel5.add(juni);

        juli.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        juli.setText("Juli");
        panel5.add(juli);

        agustus.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        agustus.setText("Agustus");
        panel5.add(agustus);

        september.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        september.setText("September");
        panel5.add(september);

        oktober.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        oktober.setText("Oktober");
        panel5.add(oktober);

        november.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        november.setText("November");
        november.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novemberActionPerformed(evt);
            }
        });
        panel5.add(november);

        desember.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        desember.setText("Desember");
        panel5.add(desember);

        jLabel7.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pilihan Bulan");

        tfuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuangActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Uang");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("Kembalian");

        tfkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkembalianActionPerformed(evt);
            }
        });

        btntotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        btnpembayaran.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnpembayaran.setText("Kirim");
        btnpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpembayaranActionPerformed(evt);
            }
        });

        tabelstatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelstatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Bulan", "Status"
            }
        ));
        jScrollPane2.setViewportView(tabelstatus);

        btnstatus.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        btnstatus.setText("Status Pembayaran");
        btnstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel9))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfuang, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btntotal))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnstatus, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 111, -1, -1));

        btnriwayat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnriwayat.setText("Riwayat Pembayaran");
        btnriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnriwayatActionPerformed(evt);
            }
        });
        panel1.add(btnriwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 327, 161, 29));

        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        panel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 368, 84, 35));

        btnkeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        panel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 368, -1, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meiActionPerformed

    private void februariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_februariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_februariActionPerformed

    private void novemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novemberActionPerformed

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfnamaActionPerformed

    private void tfkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkelasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfkelasActionPerformed

    private void tfnisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnisnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfnisnActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        // TODO add your handling code here:
        if (namaSiswa.isEmpty() || kelasSiswa.isEmpty() || nisnSiswa.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Harap mengisi data siswa terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }

        if (statusPembayaranBulan[0]) {
            januari.setEnabled(false);
            januari.setSelected(false);
        }
        if (statusPembayaranBulan[1]) {
            februari.setEnabled(false);
            februari.setSelected(false);
        }
        if (statusPembayaranBulan[2]) {
            maret.setEnabled(false);
            maret.setSelected(false);
        }
        if (statusPembayaranBulan[3]) {
            april.setEnabled(false);
            april.setSelected(false);
        }
        if (statusPembayaranBulan[4]) {
            mei.setEnabled(false);
            mei.setSelected(false);
        }
        if (statusPembayaranBulan[5]) {
            juni.setEnabled(false);
            juni.setSelected(false);
        }
        if (statusPembayaranBulan[6]) {
            juli.setEnabled(false);
            juli.setSelected(false);
        }
        if (statusPembayaranBulan[7]) {
            agustus.setEnabled(false);
            agustus.setSelected(false);
        }
        if (statusPembayaranBulan[8]) {
            september.setEnabled(false);
            september.setSelected(false);
        }
        if (statusPembayaranBulan[9]) {
            oktober.setEnabled(false);
            oktober.setSelected(false);
        }
        if (statusPembayaranBulan[10]) {
            november.setEnabled(false);
            november.setSelected(false);
        }
        if (statusPembayaranBulan[11]) {
            desember.setEnabled(false);
            desember.setSelected(false);
        }

        try {
            double sppPerBulan = 100000;
            int jumlahBulanDipilih = 0;

            if (januari.isSelected() && !statusPembayaranBulan[0]) jumlahBulanDipilih++;
            if (februari.isSelected() && !statusPembayaranBulan[1]) jumlahBulanDipilih++;
            if (maret.isSelected() && !statusPembayaranBulan[2]) jumlahBulanDipilih++;
            if (april.isSelected() && !statusPembayaranBulan[3]) jumlahBulanDipilih++;
            if (mei.isSelected() && !statusPembayaranBulan[4]) jumlahBulanDipilih++;
            if (juni.isSelected() && !statusPembayaranBulan[5]) jumlahBulanDipilih++;
            if (juli.isSelected() && !statusPembayaranBulan[6]) jumlahBulanDipilih++;
            if (agustus.isSelected() && !statusPembayaranBulan[7]) jumlahBulanDipilih++;
            if (september.isSelected() && !statusPembayaranBulan[8]) jumlahBulanDipilih++;
            if (oktober.isSelected() && !statusPembayaranBulan[9]) jumlahBulanDipilih++;
            if (november.isSelected() && !statusPembayaranBulan[10]) jumlahBulanDipilih++;
            if (desember.isSelected() && !statusPembayaranBulan[11]) jumlahBulanDipilih++;

            double totalPembayaran = jumlahBulanDipilih * sppPerBulan;
            tftotal.setText(String.valueOf(totalPembayaran));

            String uangDibayarText = tfuang.getText().trim();
            if (uangDibayarText.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap masukkan jumlah uang yang dibayar!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double uangDibayar = Double.parseDouble(uangDibayarText);

            penghitungan();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Masukkan jumlah uang yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }                                      
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatusActionPerformed
        // TODO add your handling code here:
        if (namaSiswa.isEmpty() || kelasSiswa.isEmpty() || nisnSiswa.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Belum ada data siswa yang diinputkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        updateStatusPembayaranTabel();
    }
        private void updateStatusPembayaranTabel() {
        String[] bulan = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", 
                          "Juli", "Agustus", "September", "Oktober", "November", "Desember"};

        DefaultTableModel model = (DefaultTableModel) tabelstatus.getModel();
        model.setRowCount(0);

        boolean lunasSemua = true;

        for (int i = 0; i < statusPembayaranBulan.length; i++) {
            String status = statusPembayaranBulan[i] ? "Lunas" : "Belum dibayar";
            model.addRow(new Object[]{bulan[i], status});

            if (!statusPembayaranBulan[i]) {
                lunasSemua = false;
            }
        }

        if (lunasSemua) {
            JOptionPane.showMessageDialog(null, "Pembayaran sudah lunas untuk semua bulan.", "Status Pembayaran", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Pembayaran belum lunas. Silakan cek bulan yang belum dibayar.", "Status Pembayaran", JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_btnstatusActionPerformed

    private void btndataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndataActionPerformed
        // TODO add your handling code here:
        String nama = tfnama.getText();
        String kelas = tfkelas.getText();
        String nisn = tfnisn.getText();

        if (nama.isEmpty() || kelas.isEmpty() || nisn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap mengisi semua data siswa!");
        } else {
            namaSiswa = nama;
            kelasSiswa = kelas;
            nisnSiswa = nisn;

            tfnama.setText("");
            tfkelas.setText("");
            tfnisn.setText("");

            JOptionPane.showMessageDialog(null, "Data siswa berhasil dikirim!");
        }
    }//GEN-LAST:event_btndataActionPerformed

    private void tfuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuangActionPerformed

    private void tfkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkembalianActionPerformed

    private void btnpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpembayaranActionPerformed
        // TODO add your handling code here:
        double totalPembayaran = Double.parseDouble(tftotal.getText());
        double uangDibayar = Double.parseDouble(tfuang.getText());
        if (uangDibayar < totalPembayaran) {
            JOptionPane.showMessageDialog(null, "Pembayaran kurang!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update status pembayaran bulan yang dipilih
        if (januari.isSelected()) statusPembayaranBulan[0] = true;
        if (februari.isSelected()) statusPembayaranBulan[1] = true;
        if (maret.isSelected()) statusPembayaranBulan[2] = true;
        if (april.isSelected()) statusPembayaranBulan[3] = true;
        if (mei.isSelected()) statusPembayaranBulan[4] = true;
        if (juni.isSelected()) statusPembayaranBulan[5] = true;
        if (juli.isSelected()) statusPembayaranBulan[6] = true;
        if (agustus.isSelected()) statusPembayaranBulan[7] = true;
        if (september.isSelected()) statusPembayaranBulan[8] = true;
        if (oktober.isSelected()) statusPembayaranBulan[9] = true;
        if (november.isSelected()) statusPembayaranBulan[10] = true;
        if (desember.isSelected()) statusPembayaranBulan[11] = true;

        tfuang.setText("");
        tfkembalian.setText("");
        tftotal.setText("");
        januari.setSelected(false);
        februari.setSelected(false);
        maret.setSelected(false);
        april.setSelected(false);
        mei.setSelected(false);
        juni.setSelected(false);
        juli.setSelected(false);
        agustus.setSelected(false);
        september.setSelected(false);
        oktober.setSelected(false);
        november.setSelected(false);
        desember.setSelected(false);

        JOptionPane.showMessageDialog(null, "Pembayaran berhasil dan data telah disimpan.");
    }//GEN-LAST:event_btnpembayaranActionPerformed

    private void btnriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnriwayatActionPerformed
        // TODO add your handling code here:
       if (namaSiswa.isEmpty() || kelasSiswa.isEmpty() || nisnSiswa.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Belum ada data siswa yang diinputkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

        StringBuilder riwayat = new StringBuilder();
        String[] bulan = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", 
                          "Juli", "Agustus", "September", "Oktober", "November", "Desember"};

        riwayat.append("Nama: ").append(namaSiswa).append("\n");
        riwayat.append("Kelas: ").append(kelasSiswa).append("\n");
        riwayat.append("NISN: ").append(nisnSiswa).append("\n\n");

        // Tambahkan riwayat pembayaran yang sudah dibayar
        boolean adaPembayaran = false;
        for (int i = 0; i < statusPembayaranBulan.length; i++) {
            if (statusPembayaranBulan[i]) {
                riwayat.append(bulan[i]).append(" sudah dibayar\n");
                adaPembayaran = true;
            }
        }

        if (!adaPembayaran) {
            riwayat.append("Belum ada pembayaran yang dilakukan.");
        }

        JOptionPane.showMessageDialog(null, riwayat.toString(), "Riwayat Pembayaran", JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_btnriwayatActionPerformed

    private void juniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juniActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    
        // Jika pengguna memilih "Yes", program akan ditutup
        if (pilihan == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        januari.setSelected(false);
        februari.setSelected(false);
        maret.setSelected(false);
        april.setSelected(false);
        mei.setSelected(false);
        juni.setSelected(false);
        juli.setSelected(false);
        agustus.setSelected(false);
        september.setSelected(false);
        oktober.setSelected(false);
        november.setSelected(false);
        desember.setSelected(false);

        // Reset total pembayaran
        tftotal.setText("");
        tfuang.setText("");

        // Tampilkan pesan konfirmasi
        JOptionPane.showMessageDialog(null, "Pilihan pembayaran telah dibatalkan.", "Pembatalan", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul3_no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul3_no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul3_no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul3_no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul3_no2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agustus;
    private javax.swing.JCheckBox april;
    private javax.swing.JButton btndata;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnpembayaran;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnriwayat;
    private javax.swing.JButton btnstatus;
    private javax.swing.JButton btntotal;
    private javax.swing.JCheckBox desember;
    private javax.swing.JCheckBox februari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox januari;
    private javax.swing.JCheckBox juli;
    private javax.swing.JCheckBox juni;
    private javax.swing.JCheckBox maret;
    private javax.swing.JCheckBox mei;
    private javax.swing.JCheckBox november;
    private javax.swing.JCheckBox oktober;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JCheckBox september;
    private javax.swing.JTable tabelstatus;
    private javax.swing.JTextField tfkelas;
    private javax.swing.JTextField tfkembalian;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnisn;
    private javax.swing.JTextField tftotal;
    private javax.swing.JTextField tfuang;
    // End of variables declaration//GEN-END:variables
}
